# Generated by Django 4.0.6 on 2022-09-16 05:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'HOME - Content',
                'verbose_name_plural': 'HOME - Content',
                'db_table': 'apps_backend_home_page_content',
            },
        ),
        migrations.CreateModel(
            name='HomeTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'HOME - Page Title',
                'verbose_name_plural': 'HOME - Page Title',
                'db_table': 'apps_backend_home_page_title',
            },
        ),
    ]
