# Generated by Django 4.0.6 on 2022-07-08 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del usuario', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición del usuario', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Suscription',
                'verbose_name_plural': 'Suscription',
                'db_table': 'apps_suscription',
                'ordering': ['order', 'id'],
            },
        ),
    ]
