# Generated by Django 4.0.6 on 2022-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptionmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
    ]
