# Generated by Django 4.0.6 on 2022-07-08 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email', max_length=255, verbose_name='Email')),
                ('zipCode', models.CharField(blank=True, help_text='Zip Code', max_length=12, null=True, verbose_name='Zip Code')),
                ('state', models.CharField(blank=True, help_text='State', max_length=100, null=True, verbose_name='State')),
                ('celPhone', models.CharField(help_text='Cellphone', max_length=30, verbose_name='Cellphone')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden')),
            ],
        ),
    ]
