# Generated by Django 4.0.6 on 2022-07-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelTable(
            name='contactinfo',
            table='apps_contactinfo',
        ),
    ]
