# Generated by Django 4.0.6 on 2022-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0002_alter_contactinfo_options_alter_contactinfo_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='ContactInfoModel',
        ),
    ]
