# Generated by Django 4.0.6 on 2022-07-08 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvhandlecordsmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvhandlecordsmodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvhandlecordsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tvotherinstallsmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvotherinstallsmodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvotherinstallsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tvotherquestionsmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvotherquestionsmodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvotherquestionsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tvquestionsmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvquestionsmodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvquestionsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tvsizemodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvsizemodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvsizemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tvsurfacemodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvsurfacemodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvsurfacemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tvwallmountinstallationmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvwallmountinstallationmodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvwallmountinstallationmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tvwallmountmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tvwallmountmodel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tvwallmountmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Updated', verbose_name='Updated'),
        ),
    ]
