# Generated by Django 4.0.6 on 2022-07-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicform', '0002_alter_tvhandlecordsmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvotherquestionsmodel',
            name='questions',
            field=models.ForeignKey(help_text='TV questions (other questions). Foreign key to TVQuestionsModel.', on_delete=django.db.models.deletion.CASCADE, to='dynamicform.tvquestionsmodel'),
        ),
    ]
