# Generated by Django 4.0.6 on 2022-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicform', '0003_alter_tvotherquestionsmodel_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvwallmountinstallationmodel',
            name='otherQuestions',
            field=models.ManyToManyField(blank=True, help_text='TV other questions. Required.', to='dynamicform.tvquestionsmodel'),
        ),
        migrations.DeleteModel(
            name='TVOtherQuestionsModel',
        ),
    ]
