# Generated by Django 4.0.6 on 2022-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicform', '0004_alter_tvwallmountinstallationmodel_otherquestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvwallmountinstallationmodel',
            name='otherQuestions',
            field=models.ManyToManyField(blank=True, help_text='TV other questions.', to='dynamicform.tvquestionsmodel'),
        ),
    ]
