# Generated by Django 4.0.6 on 2022-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicform', '0005_alter_tvwallmountinstallationmodel_otherquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvhandlecordsmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='tvotherinstallsmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='tvquestionsmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='tvsizemodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='tvsurfacemodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='tvwallmountinstallationmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='tvwallmountmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización', null=True, verbose_name='Orden'),
        ),
    ]
