# Generated by Django 4.0.6 on 2022-07-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0003_rename_contactinfo_contactinfomodel'),
        ('dynamicform', '0006_alter_tvhandlecordsmodel_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvwallmountinstallationmodel',
            name='user_info',
            field=models.OneToOneField(default=1, help_text='User info', on_delete=django.db.models.deletion.DO_NOTHING, to='contactinfo.contactinfomodel'),
            preserve_default=False,
        ),
    ]
